force-app/main/default/objects/Aesthetician_Coolsculpting__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arms</fullName>
            </value>
            <value>
                <fullName>Flanks</fullName>
            </value>
            <value>
                <fullName>Upper Abdomen</fullName>
            </value>
            <value>
                <fullName>Lower Abdomen</fullName>
            </value>
            <value>
                <fullName>Inner Thigh</fullName>
            </value>
            <value>
                <fullName>Outer Thigh</fullName>
            </value>
            <value>
                <fullName>Banana Roll</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>middle abdomen</fullName>
            </value>
            <value>
                <fullName>upper flank</fullName>
            </value>
            <value>
                <fullName>lower flank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aesthetician_Coolsculpting__c/fields/Chart__c.field-meta.xml
<CustomField>
    <fullName>Chart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart</label>
    <referenceTo>Chart__c</referenceTo>
    <relationshipName>Aesthetician_Coolsculptings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chart__c/Chart__c.object-meta.xml
<CustomObject>
    <label>Chart</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Chart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Esthetician_Coolsculpting_s__c/Esthetician_Coolsculpting_s__c.object-meta.xml
<CustomObject>
    <label>Esthetician Coolsculpting Treatment</label>
    <nameField>
        <label>Esthetician Coolsculpting(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Esthetician Coolsculpting Treatments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Esthetician_Coolsculpting_s__c/fields/Applicator__c.field-meta.xml
<CustomField>
    <fullName>Applicator__c</fullName>
    <label>Applicator</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coolcurve</fullName>
            </value>
            <value>
                <fullName>CoolCore</fullName>
            </value>
            <value>
                <fullName>CoolFit</fullName>
            </value>
            <value>
                <fullName>CoolMax</fullName>
            </value>
            <value>
                <fullName>CoolSmooth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Esthetician_Coolsculpting_s__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arms</fullName>
            </value>
            <value>
                <fullName>Flanks</fullName>
            </value>
            <value>
                <fullName>Upper Abdomen</fullName>
            </value>
            <value>
                <fullName>Lower Abdomen</fullName>
            </value>
            <value>
                <fullName>Inner Thigh</fullName>
            </value>
            <value>
                <fullName>Outer Thigh</fullName>
            </value>
            <value>
                <fullName>Banana Roll</fullName>
            </value>
            <value>
                <fullName>Knees</fullName>
            </value>
            <value>
                <fullName>middle abdomen</fullName>
            </value>
            <value>
                <fullName>upper flank</fullName>
            </value>
            <value>
                <fullName>lower flank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Esthetician_Coolsculpting_s__c/fields/Esthetician_Coolsculpting__c.field-meta.xml
<CustomField>
    <fullName>Esthetician_Coolsculpting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Esthetician Coolsculpting</label>
    <referenceTo>Aesthetician_Coolsculpting__c</referenceTo>
    <relationshipName>Esthetician_Coolsculptings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hydrafacial_Treatment__c/Hydrafacial_Treatment__c.object-meta.xml
<CustomObject>
    <label>Hydrafacial  Treatment</label>
    <nameField>
        <displayFormat>HT-{0000}</displayFormat>
        <label>Hydrafacial  Treatment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hydrafacial  Treatments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hydrafacial_Treatment__c/fields/Chart__c.field-meta.xml
<CustomField>
    <fullName>Chart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart</label>
    <referenceTo>Chart__c</referenceTo>
    <relationshipLabel>Hydrafacial  Treatments</relationshipLabel>
    <relationshipName>Hydrafacial_Treatments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hydrafacial_Treatment__c/fields/Cleanser__c.field-meta.xml
<CustomField>
    <fullName>Cleanser__c</fullName>
    <label>Cleanser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hydrafacial_Treatment__c/fields/Peel__c.field-meta.xml
<CustomField>
    <fullName>Peel__c</fullName>
    <label>Peel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hydrafacial_Treatment_s__c/Hydrafacial_Treatment_s__c.object-meta.xml
<CustomObject>
    <label>Hydrafacial Treatment Detail</label>
    <nameField>
        <label>Hydrafacial Treatment(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hydrafacial Treatment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hydrafacial_Treatment_s__c/fields/Booster__c.field-meta.xml
<CustomField>
    <fullName>Booster__c</fullName>
    <label>Booster</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hydrafacial_Treatment_s__c/fields/Hydrafacial_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Hydrafacial_Treatment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hydrafacial  Treatment</label>
    <referenceTo>Hydrafacial_Treatment__c</referenceTo>
    <relationshipName>Hydrafacial_Treatments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hydrafacial_Treatment_s__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Face</fullName>
            </value>
            <value>
                <fullName>Forehead</fullName>
            </value>
            <value>
                <fullName>Eyes</fullName>
            </value>
            <value>
                <fullName>Cheeks</fullName>
            </value>
            <value>
                <fullName>Left Cheek</fullName>
            </value>
            <value>
                <fullName>Right Cheek</fullName>
            </value>
            <value>
                <fullName>Lips</fullName>
            </value>
            <value>
                <fullName>Chin</fullName>
            </value>
            <value>
                <fullName>Décolleté</fullName>
            </value>
            <value>
                <fullName>Chest</fullName>
            </value>
            <value>
                <fullName>Hands</fullName>
            </value>
            <value>
                <fullName>Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hydrafacial_Treatment_s__c/fields/Serum__c.field-meta.xml
<CustomField>
    <fullName>Serum__c</fullName>
    <label>Serum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Peel__c/Peel__c.object-meta.xml
<CustomObject>
    <label>Peel</label>
    <nameField>
        <label>Peel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Peel__c/fields/Chart__c.field-meta.xml
<CustomField>
    <fullName>Chart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart</label>
    <referenceTo>Chart__c</referenceTo>
    <relationshipLabel>Peels</relationshipLabel>
    <relationshipName>Peels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UnlimitedRowsAestheticControllersUpdated.cls
public with sharing class UnlimitedRowsAestheticControllersUpdated {
    
    // Fetch recommendations based on record Id
    @AuraEnabled(cacheable=true)
    public static List<Esthetician_Coolsculpting_s__c> getRecommendations(Id recId) {
        return [SELECT Id, Area__c, Applicator__c,
                       Number__c, Minutes__c,
                       Notes__c
                FROM Esthetician_Coolsculpting_s__c
                WHERE Esthetician_Coolsculpting__c IN (SELECT Id FROM Aesthetician_Coolsculpting__c WHERE Chart__c = :recId)];
    
    }
    @AuraEnabled(cacheable=true)
    public static List<Hydrafacial_Treatment_s__c> getRecommendations2(Id recId) {
        return [SELECT Id, Location__c, Cleanser__c,
        Peel__c, Serum__c, Booster__c, Moisturizer__c, Notes__c
                FROM Hydrafacial_Treatment_s__c
                WHERE Hydrafacial_Treatment__c IN (SELECT Id FROM Hydrafacial_Treatment__c WHERE Chart__c = :recId)];
    
    }
    


    
    @AuraEnabled
    public static void updateRecommendations(List<Esthetician_Coolsculpting_s__c> recommendations) {
        try {
            update recommendations;
        } catch (Exception e) {
            throw new AuraHandledException('Error updating recommendations: ' + e.getMessage());
        }
    }
    @AuraEnabled
    public static void updateRecommendations2(List<Hydrafacial_Treatment_s__c> recommendations) {
        try {
            update recommendations;
        } catch (Exception e) {
            throw new AuraHandledException('Error updating recommendations: ' + e.getMessage());
        }
    }
    


 
    @AuraEnabled
    public static Map<String, List<String>> getPickList(String objApi, List<String> fieldApis) {
        Map<String, List<String>> picklistValuesMap = new Map<String, List<String>>();
        
        // Get the SObjectType from the objApi string
        Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(objApi);
        
        if (sObjectType != null) {
            // Iterate over each field API name
            for (String fieldApi : fieldApis) {
                List<String> picklistValues = new List<String>();
                Schema.DescribeFieldResult fieldResult = sObjectType.getDescribe().fields.getMap().get(fieldApi).getDescribe();
                
                // Iterate through picklist values and add them to the list
                for (Schema.PicklistEntry pickListVal : fieldResult.getPicklistValues()) {
                    picklistValues.add(pickListVal.getLabel());
                }
                
                // Add the picklist values to the map with the field API name as the key
                picklistValuesMap.put(fieldApi, picklistValues);
            }
        }
        system.debug(picklistValuesMap);
        return picklistValuesMap;
    }
 
    @AuraEnabled(cacheable=true)
    public static List<String> getMembershipPicklistValues() {
        List<String> picklistValues = new List<String>();
        Schema.DescribeFieldResult fieldResult = Esthetician_Coolsculpting_s__c.Area__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
 
        for (Schema.PicklistEntry entry : ple) {
            picklistValues.add(entry.getLabel());
        }
        return picklistValues;
    }
}