force-app/main/default/objects/Aesthetic_Consult_Recommendations__c/Aesthetic_Consult_Recommendations__c.object-meta.xml
<CustomObject>
    <label>Esthetic Consult Recommendations</label>
    <nameField>
        <displayFormat>Rec-{00}</displayFormat>
        <label>Aesthetic Consult Recommendations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Esthetic Consult Recommendations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aesthetic_Consult_Recommendations__c/fields/Aesthetic_consult_Area__c.field-meta.xml
<CustomField>
    <fullName>Aesthetic_consult_Area__c</fullName>
    <label>Aesthetic consult Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Glabellar</fullName>
            </value>
            <value>
                <fullName>Crows Feet</fullName>
            </value>
            <value>
                <fullName>Forehead</fullName>
            </value>
            <value>
                <fullName>Bunny Scrunch</fullName>
            </value>
            <value>
                <fullName>Chin</fullName>
            </value>
            <value>
                <fullName>Lip Flip</fullName>
            </value>
            <value>
                <fullName>Temples</fullName>
            </value>
            <value>
                <fullName>Jawline</fullName>
            </value>
            <value>
                <fullName>Right Cheek</fullName>
            </value>
            <value>
                <fullName>Left Cheek</fullName>
            </value>
            <value>
                <fullName>Chin Fat Pad</fullName>
            </value>
            <value>
                <fullName>Body Bella</fullName>
            </value>
            <value>
                <fullName>Marionette Lines</fullName>
            </value>
            <value>
                <fullName>Downward Turn Mouth</fullName>
            </value>
            <value>
                <fullName>Nasal Labial Folds</fullName>
            </value>
            <value>
                <fullName>Under Eyes</fullName>
            </value>
            <value>
                <fullName>Perioral Lines</fullName>
            </value>
            <value>
                <fullName>Lips</fullName>
            </value>
            <value>
                <fullName>Face</fullName>
            </value>
            <value>
                <fullName>nose</fullName>
            </value>
            <value>
                <fullName>Masseters</fullName>
            </value>
            <value>
                <fullName>Sculptra Body</fullName>
            </value>
            <value>
                <fullName>Jelly Roll</fullName>
            </value>
            <value>
                <fullName>Brow Lift</fullName>
            </value>
            <value>
                <fullName>neck</fullName>
            </value>
            <value>
                <fullName>Chest</fullName>
            </value>
            <value>
                <fullName>Hands</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Aesthetic_Consult_Recommendations__c/fields/Aesthetic_consult_Treatments__c.field-meta.xml
<CustomField>
    <fullName>Aesthetic_consult_Treatments__c</fullName>
    <label>Aesthetic consult Treatments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B12</fullName>
            </value>
            <value>
                <fullName>Botox</fullName>
            </value>
            <value>
                <fullName>Contour</fullName>
            </value>
            <value>
                <fullName>Dysport</fullName>
            </value>
            <value>
                <fullName>Facials/Peels</fullName>
            </value>
            <value>
                <fullName>Fractional</fullName>
            </value>
            <value>
                <fullName>FX Melasma</fullName>
            </value>
            <value>
                <fullName>IPL</fullName>
            </value>
            <value>
                <fullName>Juvederm Ultra</fullName>
            </value>
            <value>
                <fullName>Juvederm Ultra Plus</fullName>
            </value>
            <value>
                <fullName>Juvederm Voluma</fullName>
            </value>
            <value>
                <fullName>Kybella</fullName>
            </value>
            <value>
                <fullName>Kysse</fullName>
            </value>
            <value>
                <fullName>Laser Hair Removal</fullName>
            </value>
            <value>
                <fullName>LVR</fullName>
            </value>
            <value>
                <fullName>Restylane</fullName>
            </value>
            <value>
                <fullName>Restylane Defyne</fullName>
            </value>
            <value>
                <fullName>Restylane Lyft</fullName>
            </value>
            <value>
                <fullName>Restylane Refyne</fullName>
            </value>
            <value>
                <fullName>Restylane Silk</fullName>
            </value>
            <value>
                <fullName>Sculptra</fullName>
            </value>
            <value>
                <fullName>Skinvive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getObjectPicklistValue.cls
public class getObjectPicklistValue {
    @AuraEnabled(cacheable=true)
    public static Map<String, List<String>> getPicklistValues() {
        
        Map<String, List<String>> picklistValuesMap = new Map<String, List<String>>();
        List<Schema.PicklistEntry> AllPickListValue = new List<Schema.PicklistEntry>();
        
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('Aesthetic_Consult_Recommendations__c');
        system.debug('objType  '+ objType);
        
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        system.debug('objDescribe  '+ objDescribe);
        
        List<String> fieldApiNames = new List<String>{'Aesthetic_consult_Membership__c','Aesthetic_consult_Area__c','Aesthetic_consult_Treatments__c','Aesthetic_consult_Products__c'};
                    
            // Iterate through the field API names and get their descriptions
            for (String fieldApiName : fieldApiNames) {
                if (objDescribe.fields.getMap().containsKey(fieldApiName)) {
                    Schema.DescribeFieldResult fieldInfo = objDescribe.fields.getMap().get(fieldApiName).getDescribe();

                    system.debug('Field: ' + fieldApiName + ', Field Info: ' + fieldInfo);
                    
                    List<Schema.PicklistEntry> picklistValues = fieldInfo.getPicklistValues();
                    List<String> picklistValuesStr = new List<String>();
                    for (Schema.PicklistEntry pickVal : picklistValues) {
                        system.debug('Field: ' + fieldApiName + ', Picklist Value: ' + pickVal.getValue());
                        picklistValuesStr.add(pickVal.getValue());
                    }
                    system.debug('Field: ' + fieldApiName + ', Picklist Values: ' + picklistValuesStr);
                    picklistValuesMap.put(fieldApiName, picklistValuesStr);

                } else {
                    system.debug('Field not found: ' + fieldApiName);
                }
            }         
    
   			system.debug('picklistValuesMap  '+picklistValuesMap);
        
    /* Schema.DescribeSObjectResult describeResult = Aesthetic_Consult_Recommendations__c.SObjectType.getDescribe();
system.debug('describeResult  '+describeResult);

Map<String, Schema.SObjectField> fieldsMap = describeResult.fields.getMap();
system.debug('fieldsMap  '+fieldsMap);

for (String fieldName : fieldsMap.keySet()) {
system.debug('fieldName  '+fieldName);

Schema.DescribeFieldResult fieldResult = fieldsMap.get(fieldName).getDescribe();
system.debug('fieldResult  '+fieldResult);

if (fieldResult.getType() == Schema.DisplayType.PICKLIST) {
List<String> picklistValues = new List<String>();

// Retrieve the picklist values
List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();
for (Schema.PicklistEntry entry : entries) {
picklistValues.add(entry.getLabel());
}

// Add the picklist values to the map
picklistValuesMap.put(fieldName, picklistValues);
}
}
*/
    
    return picklistValuesMap;
}
    
    @AuraEnabled(cacheable=true)
    public static List<String> getPicklistValuesNew(String objectApiName, String fieldName) {
        List<String> picklistValues = new List<String>();
        Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get(objectApiName).getDescribe().fields.getMap().get(fieldName).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple) {
            picklistValues.add(f.getLabel());
        }
        return picklistValues;
    }
}