force-app/main/default/objects/CoolSculpting__c/CoolSculpting__c.object-meta.xml
<CustomObject>
    <label>CoolSculpting</label>
    <nameField>
        <label>CoolSculpting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CoolSculptings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Comments__c.field-meta.xml
<CustomField>
    <fullName>Target_Comments__c</fullName>
    <label>Target Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Patient_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Patient_Price__c</fullName>
    <label>Target Patient Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Retail_Price__c</fullName>
    <label>Target Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Savings__c.field-meta.xml
<CustomField>
    <fullName>Target_Savings__c</fullName>
    <label>Target Savings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Transform_Comments__c.field-meta.xml
<CustomField>
    <fullName>Target_Transform_Comments__c</fullName>
    <label>Target &amp; Transform Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Transform_Patient_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Transform_Patient_Price__c</fullName>
    <label>Target &amp; Transform Patient Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Transform_Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Target_Transform_Retail_Price__c</fullName>
    <label>Target &amp; Transform Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Target_Transform_Savings__c.field-meta.xml
<CustomField>
    <fullName>Target_Transform_Savings__c</fullName>
    <label>Target &amp; Transform Savings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Total_Transformation_Comments__c.field-meta.xml
<CustomField>
    <fullName>Total_Transformation_Comments__c</fullName>
    <label>Total Transformation Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Total_Transformation_Patient_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Transformation_Patient_Price__c</fullName>
    <label>Total Transformation Patient Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Total_Transformation_Retail_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Transformation_Retail_Price__c</fullName>
    <label>Total Transformation Retail Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CoolSculpting__c/fields/Total_Transformation_Savings__c.field-meta.xml
<CustomField>
    <fullName>Total_Transformation_Savings__c</fullName>
    <label>Total Transformation Savings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/createCoolsculptingFlowRecords.cls
public class createCoolsculptingFlowRecords {
	@InvocableMethod(label='Get Coolsculpting list from flow')
    
    public static void createCoolsculptingConsult(list<CoolSculpting__c> listCoolsculpting){
        System.debug(listCoolsculpting);
        List<CoolSculpting__c> insertList = new List<CoolSculpting__c>();
        for(CoolSculpting__c CS : listCoolsculpting)
        {
            CoolSculpting__c Cool  = new CoolSculpting__c();
            
            if( CS.Target_Comments__c != '' || 
               CS.Target_Transform_Comments__c != '' || 
               CS.Total_Transformation_Comments__c != '' || 
               CS.Target_Savings__c != NULL || 
               CS.Target_Transform_Savings__c != NULL || 
               CS.Total_Transformation_Savings__c != NULL || 
               CS.Target_Retail_Price__c != NULL || 
               CS.Target_Transform_Retail_Price__c != NULL || 
               CS.Total_Transformation_Retail_Price__c != NULL || 
               CS.Target_Patient_Price__c != NULL || 
               CS.Target_Transform_Patient_Price__c != NULL || 
               CS.Total_Transformation_Patient_Price__c != NULL)
            {
            	
                Cool.Name = 'Test Coolsculpting Consult';
                Cool.Target_Comments__c = CS.Target_Comments__c;
            	Cool.Target_Transform_Comments__c = CS.Target_Transform_Comments__c;
                Cool.Total_Transformation_Comments__c = CS.Total_Transformation_Comments__c;
                Cool.Target_Savings__c = CS.Target_Savings__c;
                Cool.Target_Transform_Savings__c = CS.Target_Transform_Savings__c;
                Cool.Total_Transformation_Savings__c = CS.Total_Transformation_Savings__c;
                Cool.Target_Retail_Price__c = CS.Target_Retail_Price__c;
                Cool.Target_Transform_Retail_Price__c = CS.Target_Transform_Retail_Price__c;
                Cool.Total_Transformation_Retail_Price__c = CS.Total_Transformation_Retail_Price__c;
                Cool.Target_Patient_Price__c = CS.Target_Patient_Price__c;
                Cool.Target_Transform_Patient_Price__c = CS.Target_Transform_Patient_Price__c;
                Cool.Total_Transformation_Patient_Price__c = CS.Total_Transformation_Patient_Price__c;
            	insertList.add(Cool);
            }
            
        }
        if (!insertList.isEmpty())
        {
            insert insertList;
        }
          
      }
}