force-app/main/default/objects/Botox_Dysport__c/Botox_Dysport__c.object-meta.xml
<CustomObject>
    <label>Botox/Dysport</label>
    <nameField>
        <label>Botox/Dysport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Botox/Dysport</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Botox_Dysport__c/fields/Chart__c.field-meta.xml
<CustomField>
    <fullName>Chart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart</label>
    <referenceTo>Chart__c</referenceTo>
    <relationshipLabel>Botox/Dysport</relationshipLabel>
    <relationshipName>Botox_Dysport</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Botox_Dysport__c/fields/Injectable_Notes_Botox_Dysport__c.field-meta.xml
<CustomField>
    <fullName>Injectable_Notes_Botox_Dysport__c</fullName>
    <label>Injectable Notes Botox/Dysport</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chart__c/Chart__c.object-meta.xml
<CustomObject>
    <label>Chart</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Chart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BotoxDysportController.cls
public class BotoxDysportController {
    @InvocableMethod(label='Create Botox Dysport')
    public static List<Id> createBotoxDysport(List<Botox_Dysport__c> listBotox) {
            System.debug('Received listBotox: ' + listBotox);
        List<Botox_Dysport__c> insertList = new List<Botox_Dysport__c>();
        List<Id> insertedIds = new List<Id>();
        
        // Insert records
        for(Botox_Dysport__c bot : listBotox) {
                   System.debug('Processing Botox_Dysport__c record: ' + bot);
            Botox_Dysport__c bd = new Botox_Dysport__c();
            
            if(bot.Injectable_Notes_Botox_Dysport__c != '') {
                bd.Injectable_Notes_Botox_Dysport__c = bot.Injectable_Notes_Botox_Dysport__c;
                bd.Chart__c = bot.Chart__c;
                insertList.add(bd);
            }
        }
        insert insertList;
        System.debug('insertList'+insertList);
        // Retrieve IDs of inserted records
        for(Botox_Dysport__c insertedRecord : insertList) {
            insertedIds.add(insertedRecord.Id);
        }
        
          System.debug('insertList'+insertedIds);
        return insertedIds;
    }
}